"""
Pydantic v2 schemas for the AI assistant chat interface.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatQuery(BaseModel):
    """Natural language query payload for the AI assistant."""
    question: str = Field(..., description="The user's natural language question about the analysis results.")
    session_id: Optional[str] = Field(
        default=None,
        description="Session ID from a prior pipeline run to retrieve analysis context.",
    )
    context: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional additional context to pass to the assistant.",
    )


class ChatResponse(BaseModel):
    """Response from the AI assistant, grounded in deterministic analysis results."""
    answer: str = Field(..., description="The assistant's answer based on computed analysis results.")
    data_used: List[str] = Field(
        default_factory=list,
        description="List of data sources or analysis results referenced in the answer.",
    )
    ai_powered: bool = Field(
        default=False,
        description="True if the answer was generated by an LLM; False if rule-based fallback.",
    )
    disclaimer: str = Field(
        default=(
            "This information is derived from deterministic geospatial analysis. "
            "Results should be verified with ground surveys before operational use."
        ),
        description="Mandatory disclaimer about the source and reliability of the answer.",
    )
